sudo: false
language: node_js
node_js:
  - '8'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
before_script:
  - mongo egg_dockerizer --eval 'db.createUser({user:"egg_dockerizer",pwd:"egg_dockerizer",roles:["readWrite"]});'
services:
  - mongodb
