version: '3'
services:
  mongodb:
    image: mongo:3.2
    restart: always
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=egg_dockerize
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo/:/docker-entrypoint-initdb.d/
    networks:
      - egg_dockerize
    ports:
      - 27017:27017

volumes:
  egg-mongo:  

networks:
  egg_dockerize:
    driver: bridge 